/*
Project Objective:
Analyze e-commerce sales data to understand revenue performance, customer behaviour,
product performance, and operational efficiency.
*/
select * from customers_copy;
select * from order_items_copy;
select * from orders_copy;
select * from products_copy;
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

/* Sales Performance Analysis */
/* 
Business Question 1: 
What is the total revenue generated by the company?
*/
-- SQL Query:
select round(sum(Total_Sales), 0) as Total_Revenue
from order_items_copy;
/*
Result: Total_Revenue = $21,388,472

Insight:
The company generated a total of $21.39M in revenue across all completed transactions.
*/

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

/*
Business Question 2:
How many orders were placed and what is the average order value?
*/
-- SQL Query:
select count(distinct Order_ID) as Total_Orders,
	   sum(Total_Sales)/count(distinct Order_ID) as Average_Order_Value
from order_items_copy;
/*
Result: Total_Orders = 5,000 | Average_Order_Value = $4,227.69

Insight:
The  company processed 5,000 orders at an average vale of $4,227.69 per order
*/

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

/* Sales Trend Analysis */
/*
Business Question 3:
How does monthly revenue change throughout the year?
*/
-- SQL Query:
select format(o.Order_Date,'yyyy-MM') as Sales_Month,
	   sum(oi.Total_Sales) as Monthly_Revenue
from orders_copy o
join order_items_copy oi
on o.Order_ID = oi.Order_ID
group by format(o.Order_Date,'yyyy-MM')
order by Sales_Month;
/*
Insight:
Monthly revenue stayed fairly stable across 2025, ranging from $1.62M(September, the lowest)
to $1.94M(December, the highest)
*/

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

/* Product Performance Analysis */
/*
Business Question 4:
Which product categories generate the highest revenue?
*/
-- SQL Query:
select p.Product_Category,
	   sum(oi.Total_Sales) as Revenue
from products_copy p
join order_items_copy oi
on p.Product_ID = oi.Product_ID
group by p.Product_Category
order by Revenue desc;
/*
Insight: Revenue is fairly evenly spread across the four categories — no single category dominates the business. 
Electronics leads at $5.95M (~27.8% of total revenue), narrowly ahead of Beauty and Home Appliances, 
while Fashion trails at $4.76M (~22.3%).
*/

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

/* Customer Analysis */
/*
Business Question 5:
Which cities generate the highest revenue?
*/
-- SQL Query:
select c.City, sum(Total_Sales) as Revenue
from customers_copy c
join orders_copy o
on c.Customer_ID = o.Customer_ID
join order_items_copy oi
on o.Order_ID = oi.Order_ID
group by c.City
order by Revenue desc;
/*
Insight: 
Lagos is the company's dominant market, generating $4.17M — nearly 48% more than the next-highest city, 
Warri ($2.82M), and roughly double Port Harcourt, the lowest performer.
*/

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

/* Operational Analysis */
/*
Business Question 6:
What percentage of orders are delivered, pending, shipped, or cancelled
*/
-- SQL Query
select Delivery_Status, 
	   count(*) as Total_Orders,
	   round(count(*)*100/sum(count(*)) over(), 2) as Percentage_of_Orders
from orders_copy
group by Delivery_Status;
/*
Insight:
The primary concern is that only 24% of orders are marked "Delivered", 
while 24% ("Cancelled") never complete at all, and the remaining 50% (Pending + Shipped) are still in the pipeline.
*/

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
